/* ============================================================================
   THIS IS THE ONLY FILE YOU NEED TO EDIT

   Everything Kinjal will read is in here. Change the text, reorder the
   chapters, rewrite the letter. The page rebuilds itself around it.

   PHOTOS
   You never list filenames here. Each chapter below points at a folder in
   assets/photos/ and shows every photo inside it, as a tappable stack.

   Add, remove or rename photos freely, then run:

       python3 photos.py

   That regenerates js/photos.js (the folder listing the page reads) and
   shrinks any oversized camera file so it will actually load on a phone.

   Lines marked  // EDIT  are the ones to personalise first.
   ============================================================================ */

import { PHOTOS } from "./photos.js";

export const CONTENT = {
  /* -- Who & when ------------------------------------------ */
  name: "Kinjal",
  date: "12 . 09 . 2026",

  /* -- The reveal gate -------------------------------------
     Until this moment the page shows only a countdown; the journey
     is sealed. When the clock hits zero it opens itself, no reload.

     The date is read in IST, not in whatever timezone her phone
     happens to be on, so it opens at the right moment for her.

     While editing, add to the address bar:
       ?open=1   skip the gate    ?locked=1  preview the countdown
       ?now=2026-09-11T23:59:45   pretend it is this moment          */
  reveal: {
    on: true, // false = always open
    date: "12-09-2026", // DD-MM-YYYY                        // EDIT
    time: "00:00", // 24h, the moment it opens          // EDIT
    timezone: "+05:30", // IST

    eyebrow: "not yet, my love",
    lead: "Something has been waiting all year for you. It opens on your birthday.",
    labels: {
      days: "days",
      hours: "hours",
      minutes: "minutes",
      seconds: "seconds",
    },
    dateLine: "unlocks {date}, {time}",
    peek: "no peeking. it is not yours yet 🤍",
    openingNow: "it's time…",

    /* Shown quietly on the landing once the day itself has passed.
       On the day itself, nothing is shown at all. */
    afterNoteOne: "Your birthday was yesterday. This stays yours, always.",
    afterNote: "Your birthday was {days} days ago. This stays yours, always.",
    afterNoteLater: "Made for your birthday, {date}. Still yours, always.",
  },

  /* Where the chapter folders live. Keep the trailing slash. */
  photoDir: "assets/photos/",

  /* Background music. Chopin, Nocturne in E flat major, Op. 9 No. 2.
     Public domain (CC0) from Musopen via archive.org, so it is safe to share.
     Set to null to remove the speaker button entirely. */
  music: "chopin-nocturne-op9-no2.mp3",
  musicCredit: "Chopin, Nocturne Op. 9 No. 2",

  /* -- SCENE 1 . Landing ----------------------------------- */
  landing: {
    tagline: "Something special has been waiting all year for today.", // EDIT
    cta: "Open Your Surprise",
    hint: "made only for you",
  },

  /* -- SCENE 2 . The wish ---------------------------------- */
  wish: {
    // Typed out letter by letter. Keep it short, it is the big line.
    typed: "Happy Birthday, Kinjal", // EDIT
    subtitle: "Your first birthday as my wife.", // EDIT
    note: "I could have just said it. But you deserve more than a message, so I built you a little journey instead. Take your time with it.", // EDIT
    cta: "Take a walk with me",
    // The one big framed photo. Any file from any chapter folder.
    photo: "first.png", // EDIT
  },

  /* -- SCENE 3 . Our story --------------------------------- */
  /* One entry per chapter folder, in the order she should see them.
     Every photo in `folder` is shown automatically, so there is nothing to
     list. To use only some of a folder, add e.g. photos: ['1.jpeg'].
     `PHOTOS` below is generated by photos.py. */
  story: {
    eyebrow: "chapter one",
    title: "How we got here",
    subtitle: "Seven chapters. Tap any photo to see more of it.",
    cta: "Now here's why I love you",
    stackHint: "tap for more",
    milestones: [
      // EDIT ALL
      {
        date: "where it started",
        title: "The first time we met",
        text: "Little did I know, that single moment was already pulling me in this direction.",
        folder: "1.first-time-meet",
        caption: "the beginning",
      },
      {
        date: "soon after",
        title: "Our first date",
        text: "You laughed at something I said and I remember thinking that I would like to hear that sound for a very long time.",
        folder: "2.first-date",
        caption: "first of many",
      },
      {
        date: "all the days in between",
        title: "Just enjoying you",
        text: "Long drives, bad photos, food we ordered too much of. This is the part where I stopped imagining a life without you in it.",
        folder: "3.enjoyment",
        caption: "us, being us",
      },
      {
        date: "the promise",
        title: "Our engagement",
        text: "Two families, one very loud room, and the two of us barely able to look away from each other.",
        folder: "4.engagement",
        caption: "it became real",
      },
      {
        date: "the rituals begin",
        title: "Kanku Pagla",
        text: "Red footprints, old songs, and everyone we love filling the house. The day it stopped being a plan and started being a family.",
        folder: "5.kanku-pagla",
        caption: "blessed in",
      },
      {
        date: "the day itself",
        title: "Our wedding",
        text: "A whole day of people we love, and still the only face I actually remember from it is yours.",
        folder: "6.marriage",
        caption: "yours, officially",
      },
      {
        date: "and ever since",
        title: "Life after",
        text: "Chai, arguments about dinner, the same three songs on repeat. Nobody photographs this part, and it is my favourite part.",
        folder: "7.after-marriage",
        caption: "the everyday",
      },
    ],
  },

  /* -- SCENE 4 . Reasons I love you ------------------------ */
  /* Any number works. 12 fills the grid nicely. Keep each one short. */
  reasons: {
    eyebrow: "chapter two",
    title: "Reasons I love you",
    subtitle: "Tap every heart. I hid one under each.",
    cta: "Continue",
    skip: "I'll find the rest later, continue",
    counterTemplate: "{found} of {total} found",
    list: [
      // EDIT ALL
      "The way you laugh before the joke is even finished.",
      "You remember the small things I only mentioned once.",
      "How you make any room feel like somewhere I want to stay.",
      "You are kind to people who can do nothing for you.",
      "The face you make when you are concentrating.",
      "You let me be completely myself, on my worst days too.",
      "How fiercely you love the people who are yours.",
      "You forgive faster than I deserve.",
      "The way you hum when you think nobody is listening.",
      "You make ordinary Tuesdays feel like something.",
      "You are braver than you give yourself credit for.",
      "Because after everything, you chose me.",
    ],
  },

  /* -- SCENE 5 . Make a wish ------------------------------- */
  cake: {
    title: "Make a wish",
    promptTap: "Tap each candle to blow it out",
    promptBlow: "Now blow, I can hear you",
    promptDone: "",
    candles: 5, // how many candles (3 to 8 looks best)
    iceName: "Kinjal", // piped onto the cake. '' to leave it plain
    micCta: "Use my microphone instead",
    micListening: "listening, blow gently",
    micDenied: "no problem, just tap them",
    afterword: "Your wish is safe with me.", // EDIT
    cta: "Continue",
  },

  /* -- SCENE 6 . The letter -------------------------------- */
  letter: {
    title: "I wrote you something",
    prompt: "Tap the seal to open it",
    cta: "One more thing",
    /* Your letter. Blank lines become paragraph breaks.
       Write as much as you want, the paper grows and scrolls. */
    body: `My Kinjal,

A year ago you were the person I was building a life towards. Today you are the person I am building it with, and I still catch myself surprised by how lucky that makes me.

This is your first birthday as my wife. I have thought about that sentence all week. Every birthday before this one, I was a guest in your life. This one, and every one after it, I get to be home in it.

Thank you for the patience you show me. For the way you make hard days smaller and ordinary days bigger. For laughing at my jokes even when they do not deserve it. For choosing this, and me, again every single morning.

I hope this year is generous to you. I hope it gives you rest when you need it and adventure when you want it. And whatever it brings, I will be right here, the same person, holding the same hand.

Happy birthday, my love.`, // EDIT ALL
    signature: "Always yours,\nRaj", // EDIT
    sealInitials: "R K", // pressed into the wax seal
  },

  /* -- SCENE 7 . Finale ------------------------------------ */
  finale: {
    title: "Happy Birthday",
    message: `Here is to your first year as my wife,
and to every single one after it.

I love you. Endlessly.`, // EDIT
    sign: "always, Raj", // EDIT
    replay: "Replay the journey",
    /* Leave empty to build the photo wall from every chapter automatically,
       which is what you want. */
    mosaic: [],
  },

  /* -- Hidden easter egg (small heart in the finale corner) - */
  easterEgg: {
    title: "You found it",
    subtitle: "I knew you would. A few promises for this year:",
    items: [
      // EDIT
      "That trip you keep bringing up. We are actually going.",
      "I will learn to make the one dish you miss from home.",
      "More phones-down evenings. Many more.",
      "I will keep choosing you, loudly, every day.",
    ],
  },

  /* Folder listing generated by photos.py. Do not edit. */
  _photos: PHOTOS,
};
