/* AUTO-GENERATED by photos.py. Do not edit by hand.
 * Re-run `python3 photos.py` after adding or renaming any photo. */

export const PHOTOS = {
  '1.first-time-meet': ['1.jpeg'],
  '2.first-date': ['1.jpeg'],
  '3.enjoyment': ['1.jpeg', '2.jpeg', '3.jpeg', '4.jpeg', '6.jpeg', '7.jpeg', '8.jpeg', '9.jpeg', '10.jpeg'],
  '4.engagement': ['1.jpeg', '2.jpeg', '10.jpeg', '11.jpeg', '14.JPG', '15.jpeg'],
  '5.kanku-pagla': ['1.jpeg', '112.JPG', '113.JPG', '114.JPG', '115.JPG'],
  '6.marriage': ['1.JPG', '2.JPG', '3.JPG', '5.jpg', '6.jpg', '7.jpg', '8.jpeg'],
  '7.after-marriage': ['15.jpeg', '16.jpeg', '17.jpeg'],
};
