#!/usr/bin/env python3
"""
Photo tool. Run this whenever you add, remove or rename any photo:

    python3 photos.py

It does two things:

1. SHRINKS any oversized photo, in place. Camera files can be 30-40 MB at
   9000+ pixels wide; a phone browser cannot load those. Anything bigger than
   1600px or 600 KB is resized to 1600px / quality 82. Photos already small
   enough are left completely alone.

2. WRITES js/photos.js, a list of what is actually in each chapter folder.
   The page reads that file, so you never have to type filenames into
   content.js. Drop a photo into a folder, run this, and it appears.

Chapter folders live in assets/photos/ and are ordered by their name, so the
leading numbers (1.first-time-meet, 2.first-date, ...) set the story order.

Needs Pillow:  pip3 install Pillow
"""

import pathlib
import sys

try:
    from PIL import Image, ImageOps
except ImportError:
    sys.exit("Pillow is not installed. Run:  pip3 install Pillow")

ROOT = pathlib.Path(__file__).parent
SRC = ROOT / "assets" / "photos"
MANIFEST = ROOT / "js" / "photos.js"

MAX_EDGE = 1600          # long edge in pixels
QUALITY = 82             # visually lossless at this size
SIZE_LIMIT = 600 * 1024  # anything above this gets re-encoded
EXTS = {".jpg", ".jpeg", ".png", ".webp"}


def natural_key(name: str):
    """Sort 2.jpeg before 10.jpeg, the way a person would."""
    stem = pathlib.Path(name).stem
    return (0, int(stem), name) if stem.isdigit() else (1, 0, name.lower())


def shrink(path: pathlib.Path) -> tuple[int, int] | None:
    """Resize in place if the file is too big. Returns (before, after) or None."""
    before = path.stat().st_size
    with Image.open(path) as probe:
        w, h = probe.size

    if max(w, h) <= MAX_EDGE and before <= SIZE_LIMIT:
        return None

    img = Image.open(path)
    img = ImageOps.exif_transpose(img)          # honour phone rotation
    img.thumbnail((MAX_EDGE, MAX_EDGE), Image.LANCZOS)
    img.convert("RGB").save(
        path, "JPEG", quality=QUALITY, optimize=True, progressive=True
    )
    return before, path.stat().st_size


def main() -> None:
    if not SRC.is_dir():
        sys.exit(f"No photo folder at {SRC}")

    chapters = sorted((d for d in SRC.iterdir() if d.is_dir()), key=lambda d: natural_key(d.name))
    if not chapters:
        sys.exit(f"No chapter folders inside {SRC}. Expected e.g. {SRC}/1.first-time-meet/")

    manifest: dict[str, list[str]] = {}
    shrunk = saved = total = 0

    for chapter in chapters:
        files = sorted(
            (f.name for f in chapter.iterdir() if f.suffix.lower() in EXTS),
            key=natural_key,
        )
        manifest[chapter.name] = files
        total += len(files)
        print(f"{chapter.name:22} {len(files):2} photo(s)")

        for name in files:
            result = shrink(chapter / name)
            if result:
                a, b = result
                shrunk += 1
                saved += a - b
                print(f"    shrank {name:14} {a / 1024 / 1024:6.2f} MB -> {b / 1024:5.0f} KB")

    lines = [
        "/* AUTO-GENERATED by photos.py. Do not edit by hand.",
        " * Re-run `python3 photos.py` after adding or renaming any photo. */",
        "",
        "export const PHOTOS = {",
    ]
    for folder, files in manifest.items():
        listed = ", ".join(f"'{f}'" for f in files)
        lines.append(f"  '{folder}': [{listed}],")
    lines += ["};", ""]

    MANIFEST.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST.write_text("\n".join(lines), encoding="utf-8")

    print(f"\n{total} photo(s) across {len(chapters)} chapter(s) -> {MANIFEST.relative_to(ROOT)}")
    if shrunk:
        print(f"Shrank {shrunk} oversized file(s), saved {saved / 1024 / 1024:.1f} MB.")
    else:
        print("Every photo was already web-sized, nothing to shrink.")


if __name__ == "__main__":
    main()
